version: '3.8'

services:
  # Development service
  treecast-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - SITE_URL=http://localhost:3000
    volumes:
      # Mount for development (optional)
      - ./out:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - treecast-network

  # Production-like service for testing
  treecast-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - SITE_URL=https://tricast360.de
    restart: unless-stopped
    networks:
      - treecast-network
    profiles:
      - production

networks:
  treecast-network:
    driver: bridge

# Optional: Add volumes for persistent data
volumes:
  nginx_cache:
    driver: local