[providers]
node = "18"

[phases.build]
cmds = [
  "npm ci",
  "npm run build"
]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PORT = "3000"

[staticAssets]
"public" = "./"
".next/static" = "./_next/static"